name: pinga-site
channels:
    - conda-forge
dependencies:
    - python=3.6
    - pip
    # Install Urubu's requirements from conda
    - jinja2>=2.7
    - beautifulsoup4
    - markdown
    - pygments
    - pyyaml
    - pip:
        - urubu
